apiVersion: batch/v1
kind: CronJob
metadata:
  name: invoice-processing
spec:
  schedule: "0 14 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: invoice-processing
            image: ghcr.io/cci-moc/process-csv-report:latest
            env:
              - name: GH_NONBILLABLE_DEPLOYKEY
                valueFrom:
                secretKeyRef:
                  name: gh-nonbillables
                  key: ssh-deploykey
              - name: S3_KEY_ID
                valueFrom:
                secretKeyRef:
                  name: nerc-invoices-s3-bucket
                  key: s3-key-id
              - name: S3_APP_KEY
                valueFrom:
                secretKeyRef:
                  name: nerc-invoices-s3-bucket
                  key: s3-app-key
          restartPolicy: OnFailure
