name: Integration tests

on:
  push:
  pull_request:

jobs:
  run-integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    env:
      CHROME_BIN_PATH: /usr/bin/chromium

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r process_report/tests/test-requirements.txt

      - name: Download and install latest Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium

      - name: Run integration tests
        run: |
          python -m pytest process_report/tests/integration
